<?php
$form = $this->form;
$form->get('sapid')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter sapid'
]);

$form->get('hostname')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter hostname'
]);

$form->get('loopback')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter loopback'
]);

$form->get('macaddress')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter macaddress'
]);

$form->get('archive')->setAttributes([
    'class'=>'form-control'
]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary'])->setValue('Add');
$form->setAttribute('action', $this->url('router', ['action' => 'add']));
$form->prepare();

?>

<h1>Add Router</h1>

<p>
    Please fill out the following form and click the <i>Add</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('sapid')); ?>
            <?= $this->formElement($form->get('sapid')); ?>
            <?= $this->formElementErrors($form->get('sapid')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('hostname')); ?>
            <?= $this->formElement($form->get('hostname')); ?>
            <?= $this->formElementErrors($form->get('hostname')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('loopback')); ?>
            <?= $this->formElement($form->get('loopback')); ?>
            <?= $this->formElementErrors($form->get('loopback')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('macaddress')); ?>
            <?= $this->formElement($form->get('macaddress')); ?>
            <?= $this->formElementErrors($form->get('macaddress')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('archive')); ?>
            <?= $this->formElement($form->get('archive')); ?>
            <?= $this->formElementErrors($form->get('archive')); ?>
        </div>

        <?= $this->formElement($form->get('id')); ?>
        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>