<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Router Application</span></h1>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Total Routers</h2>
            </div>
            <div class="card-body">
                <h2 class="card-title">
                    <a href="<?= $this->url('router'); ?>">
                        <?=($active+$inactive)?>
                    </a>
                </h2>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Active Routers</h2>
            </div>
            <div class="card-body">
                <h2 class="card-title">
                    <a href="<?= $this->url('router'); ?>">
                        <?=$active?>
                    </a>
                </h2>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Inactive Routers</h2>
            </div>
            <div class="card-body">
                <h2 class="card-title">
                    <a href="<?= $this->url('router'); ?>">
                        <?=$inactive?>
                    </a>
                </h2>
            </div>
        </div>
    </div>
</div>
